export default {
  entry: ['src/index.ts'],
  // format: ['esm'],
  format: ['cjs', 'esm'],
  platform: 'neutral',
  outDir: 'dist',
  bundle: true,
  splitting: false,
  sourcemap: false,
  clean: true,
  dts: true,
  minify: true,
  keepNames: false,
  pure: ['console.log', 'debug', 'assert'],
};
